db.pokeballs.remove({})

db.pokeballs.insert({ name: 'Pokeball', stock: 0 })
db.pokeballs.insert({ name: 'Great Ball', stock: 0 })
db.pokeballs.insert({ name: 'Ultra Ball', stock: 0 })
db.pokeballs.insert({ name: 'Master Ball', stock: 0 })
db.pokeballs.insert({ name: 'Drive Ball', stock: 0 })
db.pokeballs.insert({ name: 'Fast Ball', stock: 0 })
db.pokeballs.insert({ name: 'Beast Ball', stock: 0 })
db.pokeballs.insert({ name: 'Heal Ball', stock: 0 })
db.pokeballs.insert({ name: 'Level Ball', stock: 0 })
db.pokeballs.insert({ name: 'Love Ball', stock: 0 })
db.pokeballs.insert({ name: 'Friend Ball', stock: 0 })
db.pokeballs.insert({ name: 'Nest Ball', stock: 0 })
db.pokeballs.insert({ name: 'Luxury Ball', stock: 0 })
db.pokeballs.insert({ name: 'Heavy Ball', stock: 0 })
db.pokeballs.insert({ name: 'Net Ball', stock: 0 })
db.pokeballs.insert({ name: 'Moon Ball', stock: 0 })
db.pokeballs.insert({ name: 'Lure Ball', stock: 0 })
db.pokeballs.insert({ name: 'Quick Ball', stock: 0 })
db.pokeballs.insert({ name: 'Premier Ball', stock: 0 })
db.pokeballs.insert({ name: 'Timer Ball', stock: 0 })
db.pokeballs.insert({ name: 'Repeat Ball', stock: 0 })
